version: "3.9"

services:
  database:
    container_name: database
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: postgres:15.3
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
      
  heat-pump-service:
    build:
      context: ./heat_pump_service
      dockerfile: Dockerfile
      target: runtime
    container_name: heat-pump-service
    env_file:
      - .env
    environment:
      - HEAT_PUMP_IP=${HEAT_PUMP_IP}
      - HEAT_PUMP_PORT=${HEAT_PUMP_PORT}
    ports:
      - "50051:50051"
    volumes:
      - ./certs:/usr/src/app/certs

  heating-gateway:
    build:
      context: ./heating_gateway
      dockerfile: Dockerfile
      target: runtime
    container_name: heating-gateway
    depends_on:
      - database
      - heat-pump-service
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8000:80"
    volumes:
      - ./certs:/usr/src/app/certs

  pgadmin:
    container_name: pgadmin
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    image: dpage/pgadmin4
    ports:
      - "5050:80"

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
      target: runtime
    container_name: ui
    depends_on:
      - heating-gateway
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "3000:3000"

volumes:
  database-data:
    driver: local
