version: "3.9"

services:
  backend:
    build:
      args:
        - THREADS=16
      context: ./backend
      dockerfile: Dockerfile
      target: terrace-heating-backend
    container_name: backend
    ports:
      - "50051:50051"

  envoy:
    container_name: envoy
    image: envoyproxy/envoy:v1.21.0
    extra_hosts: # For Ubuntu
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"  # Proxy
      - "9901:9901"  # Admin
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml

  frontend:
    build:
      context: frontend
      dockerfile: prod.Dockerfile
    container_name: frontend
    depends_on:
      - backend
      - envoy
    environment:
      PORT: 80
    ports:
      - "80:80"
