version: "3.9"

services:
  database:
    container_name: database
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: postgres:15.3
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
      
  heat-pump-service:
    build:
      context: ./heat_pump_service
      dockerfile: Dockerfile
      target: runtime
    container_name: heat-pump-service
    env_file:
      - .env
    environment:
      - HEAT_PUMP_IP=${HEAT_PUMP_IP}
      - HEAT_PUMP_PORT=${HEAT_PUMP_PORT}
    ports:
      - "50051:50051"
    volumes:
      - ./certs:/usr/src/app/certs

  heating-gateway:
    build:
      context: ./heating_gateway
      dockerfile: Dockerfile
      target: runtime
    container_name: heating-gateway
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://+
    ports:
      - "8000:80"
    volumes:
      - ./certs:/usr/src/app/certs
      - ~/.microsoft/usersecrets/:/root/.microsoft/usersecrets

  pgadmin:
    container_name: pgadmin
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    image: dpage/pgadmin4
    ports:
      - "5050:80"
      
volumes:
  database-data:
    driver: local
