name: "Heat Pump Service"

on:
  push:
    branches: [ master ]
    paths:
      - 'heat_pump_service/**'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      matrix:
        language: [ 'cpp' ]

    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: heat_pump_service
          file: heat_pump_service/Dockerfile
          target: tests
          tags: heat-pump-service-tests
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test
        run: docker run --rm heat-pump-service-tests
